name: GitHub Test Intelligence TGS
description: Parse and collect automated test results
author: Sumit Sonar

inputs:
  results-path:
    description: Path to the JUnit XML test result file
    required: true

  api-url:
    description: URL of the GitHub Test Intelligence backend
    required: true

  api-key:
    description: API key for authenticating with the backend
    required: true

runs:
  using: node20
  main: dist/index.js